Check for HTMLFILES

diff --git a/doc/Makefile.am b/doc/Makefile.am
--- a/doc/Makefile.am
+++ b/doc/Makefile.am
@@ -1,4 +1,4 @@
-## $Id: Makefile.am,v 1.14 2004-04-11 12:13:32 adam Exp $
+## $Id: Makefile.am,v 1.15 2004-04-22 18:44:33 adam Exp $
 docdir=$(datadir)/doc/@PACKAGE@
 
 SUPPORTFILES = \
@@ -56,4 +56,19 @@ index.tkl: $(XMLFILES) tkl.xsl
 
 clean-data-hook:
 	rm -f [0-9]* *.bak
+
+dist-hook:
+	for f in $(srcdir)/*.html; do \
+		found=0; \
+		b=`basename $$f`; \
+		for h in $(HTMLFILES); do \
+			if test "$$h" = "$$b"; then \
+				found=1; \
+			fi \
+		done; \
+		if test "$$found" = "0"; then \
+			echo "$$h not found in HTMLFILES"; \
+			exit 1; \
+		fi \
+	done
 
